<a href="https://colab.research.google.com/github/Tatianacp1/MineriaDatos/blob/main/Taller_%C3%81rbolesDecisi%C3%B3n_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TALLER ÁRBOLES DE DECISIÓN.
# Tatiana Chavez Perez 

# Árbol de decisión

Según el siguiente árbol de decisión, analice y responda:

![Obama-Clinton decision tree](https://github.com/justmarkham/DAT8/raw/226791169b1cc6df8e8845c12e34e748d5ffaa85/notebooks/images/obama_clinton_tree.jpg)

## 1.1 ¿Qué son las observaciones? ¿Cuántas observaciones hay?


Las observaciones proporcionadas en el árbol de decisión de la división entre Barack Obama y Hillary Clintom son condados de los Estados Unidos con un total de 2241 condados o 2241 observaciones.

## 1.2 ¿Cuál es la variable de respuesta?


La variable respuesta es un chance entre número de condados que votan por los dos candidatos, teniendo en cuenta unas variables explicativas, representando el número de condados a favor de Barack Obama contra el número de condados a favor de Hillary Clinton o viceversa. 

## 1.3 ¿Cuáles son las características?¿Cuál es la característica más predictiva?


Las características son: <BR>
- Porcentaje de población afroamericana en cada condado.
- Tasa de graduación de secundaria.
- Ubicación del condado: Noreste/Sur o Oeste/Medio Oeste
- Si para el año del 2000 los hogares eran pobres: ¿Ganaban más o menos de $30.000?.
- Densidad de la población 
- Diferencia porcentual de los condados que votaron por Bush y Kerry en 2004 <BR>

La característica más predictiva sería el porcentaje de población afroamerica ya que es la característica principal que reduce al máximo la tasa de error y posteriormente que puede subdividir las demás características. 

## 1.4 ¿Cuál es la predicción de clase para el siguiente condado con los siguientes datos: 15% de afroamericanos, 90% de tasa de graduación en la escuela secundaria, ubicado en el Sur, alta pobreza, alta densidad de población?


Teniendo en cuenta que las características mencionadas, el condado siguiente votara por el candidato Barack Obama.

## 1.5 ¿Cuál es el chance predicha para ese mismo condado anteriormente descrito?

El chance será de 185 a 36, es decir que el candidato Barack Obama tendrá el chance de ganar con 185 condados que votan por él contra 36 condados que votan por Hillary Clinton. 

## SVM


Para esta tarea consideramos un conjunto de observaciones sobre una serie de variedades de vino tinto y blanco que implican sus propiedades químicas y su clasificación por parte de los catadores. La industria del vino ha experimentado un gran crecimiento en los últimos tiempos debido al aumento del consumo social. El precio del vino depende de un concepto bastante abstracto de apreciación del vino por parte de los catadores, cuya opinión puede tener un alto grado de variabilidad. El precio del vino depende en cierta medida de este factor tan volátil. Otro factor clave en la certificación y evaluación de la calidad del vino son las pruebas fisicoquímicas, que se realizan en laboratorio y tienen en cuenta factores como la acidez, el nivel de pH, la presencia de azúcar y otras propiedades químicas. Para el mercado del vino, sería interesante que la calidad humana de la cata pudiera relacionarse con las propiedades químicas del vino para que el proceso de certificación y evaluación de la calidad estuviera más controlado.

Se dispone de dos conjuntos de datos, uno de los cuales se refiere al vino tinto y cuenta con 1.599 variedades diferentes, y el otro, al vino blanco, con 4.898 variedades. Todos los vinos se producen en una zona concreta de Portugal. Se recogen datos sobre 12 propiedades diferentes de los vinos, una de las cuales es la calidad, basada en datos sensoriales, y el resto son propiedades químicas de los vinos, como la densidad, la acidez, el contenido de alcohol, etc. Todas las propiedades químicas de los vinos son variables continuas. La calidad es una variable ordinal con una clasificación posible de 1 (peor) a 10 (mejor). Cada variedad de vino es catada por tres catadores independientes y la clasificación final asignada es la mediana de la clasificación dada por los catadores.

Se espera que un modelo predictivo desarrollado a partir de estos datos sirva de orientación a los viñedos en cuanto a la calidad y el precio que se espera obtener de sus productos sin depender en gran medida de la volatilidad de los catadores.


In [1]:
import pandas as pd
import numpy as np

In [2]:
data_r = pd.read_csv('https://raw.githubusercontent.com/prof-tatiana-gutierrez/DatosMD/master/Wine_data_red.csv')
data_w = pd.read_csv('https://raw.githubusercontent.com/prof-tatiana-gutierrez/DatosMD/master/Wine_data_white.csv')

In [3]:
data = data_w.assign(type = 'white')

data = data.append(data_r.assign(type = 'red'), ignore_index=True)
data.sample(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
928             6.5              0.25         0.35            12.0      0.055   
1637            8.1              0.12         0.49             1.2      0.042   
3493            6.0              0.28         0.27            15.5      0.036   
2664            6.2              0.21         0.34             6.6      0.030   
3011            6.6              0.22         0.36             5.5      0.029   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
928                  47.0                 179.0  0.99800  3.58       0.47   
1637                 43.0                 160.0  0.99340  3.13       0.48   
3493                 31.0                 134.0  0.99408  3.19       0.44   
2664                 36.0                  91.0  0.99140  3.32       0.45   
3011                 30.0                 105.0  0.99206  3.20       0.47   

      alcohol  quality   type  
928      10.0        5  white  
1637      9.7        6  white  
3493     13.0        7  white  
2664     12.5        7  white  
3011     11.8        6  white

In [4]:
data.quality.value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

In [5]:
data.type.value_counts()

white    4898
red      1599
Name: type, dtype: int64

# Ejercicio 2.1

Mostrar la tabla de frecuencias de la calidad por tipo de vino.

In [ ]:
pd.crosstab(data.quality,data.type,  margins = True) 

type      red  white   All
quality                   
3          10     20    30
4          53    163   216
5         681   1457  2138
6         638   2198  2836
7         199    880  1079
8          18    175   193
9           0      5     5
All      1599   4898  6497

# Ejercicio 2.2

Teniendo en cuenta todas las variables:

* Crear un objetivo binario para cada tipo de vino, haciendo la transformación necesaria para ingresar la información al modelo.
* Crear una SVM que prediga el tipo de vino
* Evalúe con F1, AUC-ROC y log-loss


In [6]:
data['red'] = data['type'].map({'white':0, 'red':1}).astype(np.int)
data.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality   type  red  
0      8.8        6  white    0  
1      9.5        6  white    0  
2     10.1        6  white    0  
3      9.9        6  white    0  
4      9.9        6  white    0

In [7]:
data = data.drop(['type'],axis=1)
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  red  
0      8.8        6    0  
1      9.5        6    0  
2     10.1        6    0  
3      9.9        6    0  
4      9.9        6    0

In [10]:
from sklearn import metrics
from scipy import stats
import seaborn as sns
from sklearn.datasets import make_blobs
import warnings
warnings.filterwarnings('ignore')
from pickle import TRUE
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split


In [ ]:
X = data.drop(['red'],axis=1)
y = data.red
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state =1234)
modSVC = SVC(kernel='linear', C=1E6, probability=True)
modSVC.fit(X_train, y_train)

SVC(C=1000000.0, kernel='linear', probability=True)

In [ ]:
y_pred=modSVC.predict(X_test)
y_pred

array([1, 0, 1, ..., 0, 1, 0])

In [ ]:
y_pred_prob=modSVC.predict_proba(X_test)
y_pred_prob

array([[3.00000090e-14, 1.00000000e+00],
       [9.99992572e-01, 7.42846588e-06],
       [1.10568352e-06, 9.99998894e-01],
       ...,
       [9.99996670e-01, 3.33004235e-06],
       [1.05430504e-07, 9.99999895e-01],
       [9.99973170e-01, 2.68297936e-05]])

In [ ]:
print("Variable real:")
print(np.array(np.unique(y_test, return_counts=True)).T)
print("Variable predicha:" )
print(np.array(np.unique(y_pred, return_counts=True)).T)

Variable real:
[[  0 966]
 [  1 334]]
Variable predicha:
[[  0 976]
 [  1 324]]


In [ ]:
print('Fbeta score:', metrics.fbeta_score(y_test, y_pred, beta=0.5))
print('Log Loss:', metrics.log_loss(y_test, y_pred_prob))
print('ROC AUC score:', metrics.roc_auc_score(y_test, y_pred, average=None))

Fbeta score: 0.9785276073619631
Log Loss: 0.07229335430019956
ROC AUC score: 0.9749569184612142


In [ ]:
metricas = pd.DataFrame({'Modelo' : ['Modelo linear']})
metricas['F1'] = (metrics.fbeta_score(y_test, y_pred, beta=0.5))
metricas['Log Loss'] = (metrics.log_loss(y_test, y_pred_prob))
metricas['ROC AUC']=(metrics.roc_auc_score(y_test, y_pred, average=None))
metricas

Modelo        F1  Log Loss   ROC AUC
0  Modelo linear  0.978528  0.072293  0.974957

# Ejercicio 2.3

* Probar la SVM utilizando los diferentes kernels ('poly', 'rbf', 'sigmoid')
* Evalúe con F1, AUC-ROC y log-loss


In [ ]:
modSVC = SVC(kernel='poly', C=1E6,probability=True)
modSVC.fit(X_train, y_train)
y_pred=modSVC.predict(X_test)
y_pred_prob=modSVC.predict_proba(X_test)

print("Variable real:")
print(np.array(np.unique(y_test, return_counts=True)).T)
print("Variable predicha:" )
print(np.array(np.unique(y_pred, return_counts=True)).T)
f2=metrics.fbeta_score(y_test, y_pred, beta=0.5)
l2=metrics.log_loss(y_test, y_pred_prob)
r2=metrics.roc_auc_score(y_test, y_pred, average=None)

Variable real:
[[  0 966]
 [  1 334]]
Variable predicha:
[[  0 971]
 [  1 329]]


In [ ]:
modSVC = SVC(kernel='rbf', C=1E6,probability=True)
modSVC.fit(X_train, y_train)
y_pred=modSVC.predict(X_test)
y_pred_prob=modSVC.predict_proba(X_test)

print("Variable real:")
print(np.array(np.unique(y_test, return_counts=True)).T)
print("Variable predicha:" )
print(np.array(np.unique(y_pred, return_counts=True)).T)
f3=metrics.fbeta_score(y_test, y_pred, beta=0.5)
l3=metrics.log_loss(y_test, y_pred_prob)
r3=metrics.roc_auc_score(y_test, y_pred, average=None)

Variable real:
[[  0 966]
 [  1 334]]
Variable predicha:
[[  0 970]
 [  1 330]]


In [ ]:
modSVC = SVC(kernel='sigmoid', C=1E6,probability=True)
modSVC.fit(X_train, y_train)
y_pred=modSVC.predict(X_test)
y_pred_prob=modSVC.predict_proba(X_test)

print("Variable real:")
print(np.array(np.unique(y_test, return_counts=True)).T)
print("Variable predicha:" )
print(np.array(np.unique(y_pred, return_counts=True)).T)
f4=metrics.fbeta_score(y_test, y_pred, beta=0.5)
l4=metrics.log_loss(y_test, y_pred_prob)
r4=metrics.roc_auc_score(y_test, y_pred, average=None)

Variable real:
[[  0 966]
 [  1 334]]
Variable predicha:
[[  0 981]
 [  1 319]]


In [ ]:
metricas = pd.DataFrame({'Modelo' : ['Modelo poly','Modelo rbf','Modelo sigmoid']})
metricas['Fbeta score 0.5'] = (f2,f3,f4)
metricas['Log Loss'] = (l2,l3,l4)
metricas['ROC AUC']=(r2,r3,r4)
metricas.sort_values(by = ['Fbeta score 0.5', 'ROC AUC','Log Loss'], ascending = [False, False,True], na_position = 'first')

Modelo  Fbeta score 0.5  Log Loss   ROC AUC
1      Modelo rbf         0.973398  0.080968  0.977895
0     Modelo poly         0.969697  0.119823  0.974384
2  Modelo sigmoid         0.757764  0.522528  0.826450

# Ejercicio 2.4
* Utilizando el mejor SVM del punto anterior encontrar los parámetros que da el mejor rendimiento teniendo en cuenta los siguientes hiperparámetros
'C': [0.1, 1, 10, 100, 1000], 'gamma': [0.01, 0.001, 0.0001]
* Evalúe cada modelo con F1, AUC-ROC y log-loss

Nota: Para los valores de C y gamma, deben realizar todas las posibles combinaciones entre estas dos variables.

**El kernel con mejor rendimiento presentado en el punto anterior es el kernel rbf**

In [ ]:
from sklearn.svm import SVC
from sklearn import metrics

c = [0.1, 1, 10, 100, 1000]
gamma =  [0.01, 0.001, 0.0001]
metricas=pd.DataFrame(columns=['C', 'Gamma', 'Fbeta score 0.5','Log Loss','ROC AUC'],index=range(15))
m=0
for i in c:
  for j in gamma:
    modSVC = SVC(kernel='rbf', C=i,gamma=j,probability=True)
    modSVC.fit(X_train, y_train)
    y_pred=modSVC.predict(X_test)
    y_pred_prob =modSVC.predict_proba(X_test)
    metricas.iloc[[m],0]=i
    metricas.iloc[[m],1]=j
    metricas.iloc[[m],2]= metrics.fbeta_score(y_test, y_pred, beta=0.5).round(7)
    metricas.iloc[[m],3] = metrics.log_loss(y_test, y_pred_prob).round(7)
    metricas.iloc[[m],4] = metrics.roc_auc_score(y_test, y_pred, average=None).round(7)
    m+=1
print(metricas)

       C   Gamma Fbeta score 0.5  Log Loss   ROC AUC
0    0.1    0.01        0.908135  0.223666  0.880478
1    0.1   0.001        0.901526  0.230185  0.880422
2    0.1  0.0001        0.894625   0.22978  0.869943
3      1    0.01        0.922104  0.168266  0.906907
4      1   0.001        0.909405  0.197301  0.885949
5      1  0.0001        0.910987  0.203142  0.884969
6     10    0.01        0.956522  0.101702  0.955384
7     10   0.001        0.932983  0.124969  0.918421
8     10  0.0001         0.92953  0.156749  0.908459
9    100    0.01        0.972393  0.081826  0.970928
10   100   0.001        0.974785  0.081961  0.971445
11   100  0.0001        0.958816  0.098337  0.942485
12  1000    0.01        0.973072  0.087846  0.972425
13  1000   0.001        0.976421   0.07956   0.97991
14  1000  0.0001        0.982695  0.072284  0.974495


In [ ]:
metricas.sort_values(by = ['Fbeta score 0.5', 'ROC AUC','Log Loss'], ascending = [False, False,True], na_position = 'first')

C   Gamma Fbeta score 0.5  Log Loss   ROC AUC
14  1000  0.0001        0.982695  0.072284  0.974495
13  1000   0.001        0.976421   0.07956   0.97991
10   100   0.001        0.974785  0.081961  0.971445
12  1000    0.01        0.973072  0.087846  0.972425
9    100    0.01        0.972393  0.081826  0.970928
11   100  0.0001        0.958816  0.098337  0.942485
6     10    0.01        0.956522  0.101702  0.955384
7     10   0.001        0.932983  0.124969  0.918421
8     10  0.0001         0.92953  0.156749  0.908459
3      1    0.01        0.922104  0.168266  0.906907
5      1  0.0001        0.910987  0.203142  0.884969
4      1   0.001        0.909405  0.197301  0.885949
0    0.1    0.01        0.908135  0.223666  0.880478
1    0.1   0.001        0.901526  0.230185  0.880422
2    0.1  0.0001        0.894625   0.22978  0.869943

# Ejercicio 2.5

Compare los resultados con todos los anteriores modelos y eliga ¿Cuál algoritmo con cuáles hiperparámetros es el que tiene mejor rendimiento según la puntuación F1, AUC-ROC y log-loss?

Según los resultados se puede observar que con los hiperparámetros C = 1000 y gamma = 0.0001 o un gamma = 0.001 y un kernel = rbf, se obtienen los mejores rendimientos. Sin embargo para comprobar lo anterior se opta por realizar una validación cruzada con los modelos anteriormente propuestos. 

In [19]:
from sklearn.model_selection import KFold
from sklearn import metrics
from sklearn.preprocessing import label_binarize

data2 = data.copy()
data2['red'] = data['red'].map({1:0, 0:1}).astype(np.int)

X = np.array(data2.drop(['red'],axis=1))
y = np.array(data2['red'])

c = [0.1, 1, 10, 100, 1000]
gamma =  [0.01, 0.001, 0.0001]
metricas=pd.DataFrame(columns=['C', 'Gamma', 'Fbeta score 0.5','Log Loss','ROC AUC'],index=range(15))
m=0

kf = KFold(n_splits=5)
outcomes = []
fold = 0

for train_index, test_index in kf.split(X):
  fold += 1
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]
  for i in c:
    for j in gamma:
      modSVC = SVC(kernel='rbf', C=i,gamma=j,probability=True)
      modSVC.fit(X_train, y_train)
      y_pred=modSVC.predict(X_test)
      y_pred_prob =modSVC.predict_proba(X_test)
      fbeta = metrics.fbeta_score(y_test, y_pred, beta=0.5).round(7)
      cont=0
      for m in range(len(y_test)):
        if y_test[m] == 1:
          cont = cont+1
      if cont == len(y_test):
        log=0
      else:
        log = metrics.log_loss(y_test, y_pred_prob).round(7)         
      cont1=0
      for m in range(len(y_test)):
        if y_test[m] == 1:
          cont1 = cont1+1
      if cont1 == len(y_test):
        roc=0
      else:
        roc = metrics.roc_auc_score(y_test, y_pred, average=None).round(7)      
      print(f'C = {i}, gamma = {j}')
      outcomes.append(fbeta)
      outcomes.append(log)
      outcomes.append(roc)
      m=+1
      print("Fold {0} F BETA: {1} Log-Loss: {2} ROC AUC: {3}".format(fold, fbeta,log,roc))

      print("------")    
mean_outcome = np.mean(outcomes)
print("AUC Promedio: {0}".format(mean_outcome))  


C = 0.1, gamma = 0.01
Fold 1 F BETA: 0.9962523 Log-Loss: 0 ROC AUC: 0
------
C = 0.1, gamma = 0.001
Fold 1 F BETA: 0.9948178 Log-Loss: 0 ROC AUC: 0
------
C = 0.1, gamma = 0.0001
Fold 1 F BETA: 0.9925539 Log-Loss: 0 ROC AUC: 0
------
C = 1, gamma = 0.01
Fold 1 F BETA: 0.9943361 Log-Loss: 0 ROC AUC: 0
------
C = 1, gamma = 0.001
Fold 1 F BETA: 0.9948178 Log-Loss: 0 ROC AUC: 0
------
C = 1, gamma = 0.0001
Fold 1 F BETA: 0.9954574 Log-Loss: 0 ROC AUC: 0
------
C = 10, gamma = 0.01
Fold 1 F BETA: 0.9956168 Log-Loss: 0 ROC AUC: 0
------
C = 10, gamma = 0.001
Fold 1 F BETA: 0.994978 Log-Loss: 0 ROC AUC: 0
------
C = 10, gamma = 0.0001
Fold 1 F BETA: 0.995138 Log-Loss: 0 ROC AUC: 0
------
C = 100, gamma = 0.01
Fold 1 F BETA: 0.994978 Log-Loss: 0 ROC AUC: 0
------
C = 100, gamma = 0.001
Fold 1 F BETA: 0.9978274 Log-Loss: 0 ROC AUC: 0
------
C = 100, gamma = 0.0001
Fold 1 F BETA: 0.9965689 Log-Loss: 0 ROC AUC: 0
------
C = 1000, gamma = 0.01
Fold 1 F BETA: 0.993529 Log-Loss: 0 ROC AUC: 0
------

ValueError: ignored

Se puede evidenciar que con los hiperparámetros C = 1000, gamma = 0.001 o gamma = 0.0001 son los valores más altos en los valores de K-Fold, más específicamente en el fold=2 y fold=3, para el fold=5 y en algunas métricas =0, se evidencia que con la advertencia en la mayoría de las particiones hay valores de una sola clase, siendo no significativas las métricas para estos casos. 


In [21]:
X = np.array(data2.drop(['red'],axis=1))
y = np.array(data2['red'])

kf = KFold(n_splits=5)
outcomes = []
fold = 0
for train_index, test_index in kf.split(X):
  fold += 1
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]
  modSVC = SVC(kernel='rbf', C=1000,gamma=0.001,probability=True)
  modSVC.fit(X_train, y_train)
  predictions = modSVC.predict(X_test)
  roc = metrics.fbeta_score(y_test, predictions, beta=0.5)
  outcomes.append(roc)
  print("Fold {0} AUC: {1}".format(fold, roc))
  print("------")    
mean_outcome = np.mean(outcomes)
print("AUC Promedio: {0}".format(mean_outcome))  

Fold 1 AUC: 0.9976708074534162
------
Fold 2 AUC: 0.9987631416202846
------
Fold 3 AUC: 0.9976689976689976
------
Fold 4 AUC: 0.9786687734544737
------
Fold 5 AUC: 0.0
------
AUC Promedio: 0.7945543440394344


In [22]:
X = np.array(data2.drop(['red'],axis=1))
y = np.array(data2['red'])

kf = KFold(n_splits=5)
outcomes = []
fold = 0
for train_index, test_index in kf.split(X):
  fold += 1
  X_train, X_test = X[train_index], X[test_index]
  y_train, y_test = y[train_index], y[test_index]
  modSVC = SVC(kernel='rbf', C=1000,gamma=0.0001,probability=True)
  modSVC.fit(X_train, y_train)
  predictions = modSVC.predict(X_test)
  roc = metrics.fbeta_score(y_test, predictions, beta=0.5)
  outcomes.append(roc)
  print("Fold {0} AUC: {1}".format(fold, roc))
  print("------")    
mean_outcome = np.mean(outcomes)
print("AUC Promedio: {0}".format(mean_outcome))  

Fold 1 AUC: 0.997983870967742
------
Fold 2 AUC: 0.9986076732673267
------
Fold 3 AUC: 0.9982948380096108
------
Fold 4 AUC: 0.9808565225971975
------
Fold 5 AUC: 0.0
------
AUC Promedio: 0.7951485809683755


**En conclusión se puede optar por escoger un modelo con Kernel = rbf con hiperparámetros C=1000 y gamma=0.001 y teniendo en cuenta la métrica Fbeta score con beta = 0.5 y deberían tomar una validación cruzada con un k fold igual a 2.**